routes/web.php
<?php

Route::group(['middleware' => 'guest'], function() {
    Route::get('/login', ['as'=>'auth.login' , 'uses' => 'Backend\AuthController@login']);
    Route::post('/login',[
        'as'=>'auth.postLogin', 'uses' => 'Backend\AuthController@postLogin']);
});
Route::group([
        'prefix'        => 'admin',
        'namespace'     => 'Backend',
        'middleware'    => 'auth'
    ],function() {
    Route::get('/', ['uses' => 'AuthController@index', 'as' => 'index']);
    Route::get('/logout',['as'=> 'auth.logout','uses'=> 'AuthController@logout']);
    Route::resource('/food', 'FoodController',
        [
            'except' => ['destroy']
        ]);
    Route::get('food/{id}/delete', ['as'=>'food.delete','uses'=>'FoodController@delete']);
    Route::get('customer/',['as'=> 'customer.index', 'uses'=>'CustomerController@index']);
    Route::get('customer/{id}/show',[
        'as'    => 'customer.show',
        'uses'  =>'CustomerController@show'
    ]);
    Route::get('customer/{id}/edit',[
        'as'    =>'customer.edit',
        'uses'  =>'CustomerController@edit'
    ]);
    Route::put('customer/{id}/update',[
        'as'    => 'customer.update',
        'uses'  => 'CustomerController@update'
    ]);
    Route::get('customer/{id}/delete',[
        'as'    => 'customer.delete',
        'uses'  => 'CustomerController@delete',
    ]);
    Route::get('driver/', [
        'as'    =>'driver.index',
        'uses'  =>'DriverController@index'
    ]);
    Route::get('driver/create', [
        'as'    =>'driver.create',
        'uses'  =>'DriverController@create'
    ]);
    Route::post('driver/store', [
        'as'    =>'driver.store',
        'uses'  =>'DriverController@store'
    ]);
    Route::get('driver/{id}/show',[
        'as'    => 'driver.show',
        'uses'  => 'DriverController@show'
    ]);
    Route::get('driver/{id}/edit',[
        'as'    => 'driver.edit',
        'uses'  => 'DriverController@edit'
    ]);
    Route::put('driver/{id}/update',[
        'as'    => 'driver.update',
        'uses'  => 'DriverController@update'
    ]);
    Route::get('driver/{id}/delete',[
        'as'    => 'driver.delete',
        'uses'  => 'DriverController@delete'
    ]);
    Route::get('orders/index', [
        'as'=> 'order.index',
        'uses'=>'OrderController@index'
    ]);
    Route::get('orders/{id}/show', [
        'as'=> 'order.show',
        'uses'=>'OrderController@show'
    ]);
    Route::get('order/{id}/delete', [
        'as' => 'order.delete',
        'uses' => 'OrderController@delete'
    ]);
    Route::get('pembayaran/index', [
        'as' => 'pembayaran.index',
        'uses' => 'PembayaranController@index'
    ]);

    Route::get('pembayaran/{id}/change-status/{status}/order-id/{orderid}', [
        'as' => 'pembayaran.change',
        'uses' => 'PembayaranController@changeStatus'
    ]);

    Route::get('pengiriman/index', ['as'=>'pengiriman.index','uses'=>'PengirimanController@index']);
    // Route::get('guzzle/index', ['as'=>'pengiriman.index','uses'=>'TalithaController@belajarGuzzle']);
});

app/Http/Controllers/Api/FoodController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Models\Food;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Auth;

class FoodController extends Controller
{
    public function index()
    {
        $data = Food::all();

        $responGagal = [
            'status'=> 400,
            'keterangan'=> 'No Data!',
        ];

        if (count($data) > 0) {
            return response()->json([
                'status'=>200,
                'data' => $data
            ],200);
        } else {
            return response()->json($responGagal);
        }
    }

    public function show($id)
    {
        $food = Food::find($id);
        return response()->json(['status'=>200,'data'=>$food],200);
    }
}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use Auth;
use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\User;

class AuthController extends Controller
{
    public function index()
    {
        return view('backend.templates.default');
    }

    public function login(Request $request)
    {
        return view('backend.auth.login', [
            'title' => 'Login User',
        ]);
    }

    public function postLogin(Request $request)
    {
        $this->validate($request, [
            'email'     => 'required|email',
            'password'  => 'required',
        ]);

        if(!Auth::attempt([
            'email'     => $request->email,
            'password'  => $request->password,
        ])) {
            return redirect()->back()->with('danger', 'detail login salah');
        }

        return redirect()->route('index')->with('info', 'Berhasil login');
    }

    public function logout()
    {
        Auth::logout();

        return redirect()
                ->route('auth.login')
                ->with('info', 'You have logged out');
    }

    public function customerPostLogin(Request $request)
    {
        $customer = auth()->guard('customers');

        $credentials = [
            'email'     => $request->email,
            'password'  => $request->password,
        ];

        if ($customer->attempt($credentials)) {
            return redirect('customer');
        }else {
            return 'information access denied';
        }
    }
}

app/Http/Controllers/Backend/CustomerController.php
<?php

namespace App\Http\Controllers\Backend;

use File;
use App\Http\Requests;
use App\Models\Customer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CustomerController extends Controller
{
    protected $customer;

    public function __construct()
    {
        $this->customer = new Customer;
    }

    public function index()
    {
        $customers = $this->customer->paginate(10);

        return view('backend.customer.index',[
            'customers' => $customers
        ]);
    }

    public function show($id)
    {
        $customer = $this->customer->find($id);

        return view('backend.customer.show',[
            'customer' => $customer
        ]);
    }

    public function edit($id)
    {
        $customer = $this->customer->find($id);

        return view('backend.customer.edit',[
            'customer' => $customer
        ]);
    }

    public function update(Request $request,$id)
    {
        $rules = [
            'name'          => 'required',
            'email'         => 'required',
            'repassword'    => 'same:password|min:5',
            'phone'         => 'required|numeric',
            'address'       => 'required',
            'image'         => 'image',
            'city'          => 'required',
        ];

        $this->validate($request,$rules);
        $this->customer->updateData($request,$id);

        return redirect()->route('customer.index')
                        ->with('info','Berhasil meng update!');
    }

    public function delete($id)
    {
        $customer = $this->customer->find($id);

        if (File::isFile($customer->image)){
            File::delete($customer->image);
        }
        $customer->delete();

        return redirect()->route('customer.index')
                    ->with('info','Berhasil menghapus!');
    }
}

app/Http/Controllers/Backend/DriverController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Models\Driver;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use File;

class DriverController extends Controller
{
    protected $driver;

    public function __construct()
    {
        $this->driver = new Driver();
    }

    public function index()
    {
        $drivers = $this->driver->paginate(10);

        return view('backend.driver.index',[
            'drivers' => $drivers
        ]);
    }

    public function create()
    {
        return view('backend.driver.add');
    }

    public function store(Request $request)
    {
        $rules = [
            'name'        => 'required|min:3',
            'email'       => 'required|email|unique:drivers',
            'password'    => 'required|min:3',
            'repassword'  => 'same:password|min:5',
            'image'       => 'required|image',
            'city'        => 'required',
            'gender'      => 'required',
            'address'     => 'required',
            'no_ktp'      => 'required|numeric|min:3',
            'no_telp'     => 'required|numeric|min:3',
            'no_sim'      => 'required|numeric|min:3',
        ];

        $this->validate($request,$rules);
        $this->driver->insert($request);

        return redirect()->route('driver.index')
                ->with('success','Berhasil menambahkan driver!');
    }

    public function show($id)
    {
        $driver = $this->driver->find($id);

        return view('backend.driver.show',[
            'driver' => $driver
        ]);
    }

    public function edit($id)
    {
        $driver = $this->driver->find($id);

        return view('backend.driver.edit',[
            'driver' => $driver
        ]);
    }

    public function update(Request $request,$id)
    {
        $rules = [
            'name'        => 'required|min:3',
            'email'       => 'required|email',
            'repassword'  => 'same:password',
            'image'       => 'image',
            'city'        => 'required',
            'gender'      => 'required',
            'address'     => 'required',
            'no_ktp'      => 'required|numeric|min:3',
            'no_telp'     => 'required|numeric|min:3',
            'no_sim'      => 'required|numeric|min:3',
        ];

        $this->validate($request,$rules);
        $this->driver->updateDriver($request,$id);

        return redirect()->route('driver.index')
                    ->with('info','Berhasil Update!');
    }

    public function delete($id)
    {
        $driver             = $this->driver->find($id);
        $oldFotoLocation    = $driver->image;

        if (File::isFile($oldFotoLocation)){
            File::delete($oldFotoLocation);
        }

        $driver->delete();

        return redirect()->route('driver.index')
                    ->with('info','berhasil delete driver');
    }
}

app/Http/Controllers/Backend/FoodController.php
<?php

namespace App\Http\Controllers\Backend;

use File;
use DB;
use App\Models\Food;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FoodController extends Controller
{
    protected $food;

    public function __construct()
    {
        $this->food = new Food();
    }

    public function index(Request $request)
    {
        $nama = DB::table('foods')->where('name_food','LIKE','%'.$request->name.'%')
                    ->paginate(5);
        $food = $nama;

        return view('backend.food.index',[
            'foods' => $food
        ]);
    }

    public function create()
    {
        return view('backend.food.add');
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name_food' => 'required',
            'price'     => 'required|numeric',
            'image'     => 'required|image',
            'stock'     => 'required'
        ]);

        $this->food->store($request);

        return redirect()->route('food.index')
                ->with('success','Makanan berhasil di tambahkan');
    }

    public function show($id)
    {
        $food = $this->food->find($id);
        return view('backend.food.show',[
            'food' => $food
        ]);
    }

    public function edit($id)
    {
        $food = $this->food->find($id);

        return view('backend.food.edit',[
            'food' => $food
        ]);
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'image' => 'image'
        ]);

        $this->food->updateData($request,$id);

        return redirect()->route('food.index')->with('success','Makanan Updated');
    }

    public function delete($id)
    {
        $food = $this->food->find($id);

        if (File::isFile($food->image)){
            File::delete($food->image);
        }

        $food->delete();

        return redirect()->route('food.index')
                    ->with('info','berhasil delete makanan');
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Http\Requests;

class OrderController extends Controller
{
    protected $orderDetail;

    public function __construct()
    {
        $this->orderDetail = new OrderDetail();
    }

    public function index()
    {
        $orders = Order::with('customer')->orderBy('id','desc')->paginate(5);

        return view('backend.order.index',[
            'orders' => $orders
        ]);
    }

    public function show($id)
    {
        $total = 0;
        $details = $this->orderDetail->where('order_id','=',$id)->get();
        $order = Order::find($id);

        foreach ($details as $detail) {
            $total +=$detail->subtotal;
        }

        return view('backend.order.show',[
            'details'   => $details,
            'total'     => $total,
            'order'     => $order,
            'no'        =>1
        ]);
    }

    public function delete($id)
    {
        $order = Order::find($id);
        $order->delete();

        return redirect()->route('order.index')->with('info','Delete Sukses!');
    }
}

app/Http/Controllers/Backend/PembayaranController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helpers\Fcm;
use App\Models\Order;
use App\Models\Driver;
use App\Models\Customer;
use App\Models\Pembayaran;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PembayaranController extends Controller
{
    protected $status;

    public function index()
    {
        $pembayaran = Pembayaran::orderBy('id','desc')->with(['order' => function($order){
            $order->with('customer');
        }])->paginate(10);

        // $pdf = view('others.pdf', $data);

        return view('backend.pembayaran.index',['pembayaran' => $pembayaran]);
    }

    public function changeStatus($id,$status,$orderId)
    {
        $fcm = new Fcm();
        $pembayaran = Pembayaran::find($id);
        $order = Order::with('orderDetails')->find($orderId);
        $drivers = Driver::all();
        $tokenUser = [];

        foreach ($drivers as $driver) {
            $tokenUser[] = $driver->fcm_id;
        }

        $message = [
            'title'=>'Order Baru',
            'body'=> $order
        ];

        $fcm->sendMessage($tokenUser,$message);

        $pembayaran->payment_status = $status;
        $pembayaran->save();

        return redirect()->route('pembayaran.index');
    }
}

app/Http/Controllers/Backend/PengirimanController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Pengiriman;

class PengirimanController extends Controller
{
    public function index()
    {
        $pengiriman = Pengiriman::paginate(10);

        return view('backend.pembayaran.pengiriman',[
            'pengirimans'=>$pengiriman
        ]);
    }
}

app/Http/Controllers/Backend/TalithaController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use GuzzleHttp\Client;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class TalithaController extends Controller
{
    public function talitha()
    {
        return view('backend.templates.talitha');
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class UserController extends Controller
{

}

resources/views/backend/food/add.blade.php
@extends('backend.templates.default')
@section('content')
    <form action="{{ route('food.store') }}" method="post" enctype="multipart/form-data">
    <h1 align="center" class="panel panel-heading">Tambah Makanan</h1>
        <div class="form-group row">
          <label for="name_food" class="col-xs-1 col-form-label">Name</label>
          <div class="col-xs-10 {{ $errors->has('name_food') ? ' has-error ' : '' }}">
            <input class="form-control" type="text" name="name_food"  >
          @if ($errors->has('name_food'))
            <span class="help-block">{{ $errors->first('name_food') }}</span>
          @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="price" class="col-xs-1 col-form-label">Price</label>
           <div class="col-xs-10 {{ $errors->has('price') ? ' has-error ' : '' }}">
            <input class="form-control" type="number" name="price" >
            @if ($errors->has('price'))
                <span class="help-block">{{ $errors->first('price') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="example-url-input" class="col-xs-1 col-form-label">Image</label>
          <div class="col-xs-10 {{ $errors->has('image') ? ' has-error ' : '' }}">
            <input class="form-control" type="file" name="image" accept="image/*" id="example-url-input">
          @if ($errors->has('image'))
                <span class="help-block">{{ $errors->first('image') }}</span>
          @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="example-email-input" class="col-xs-1 col-form-label">Diskon</label>
          <div class="col-xs-10 {{ $errors->has('discount') ? ' has-error ' : '' }}">
            <input class="form-control" name="discount" type="number" value="" id="example-email-input">
             @if ($errors->has('discount'))
                <span class="help-block">{{ $errors->first('discount') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="example-number-input" class="col-xs-1 col-form-label">Stok</label>
          <div class="col-xs-10 {{ $errors->has('stock') ? ' has-error ' : '' }}">
            <input class="form-control" name="stock" type="number" value="" id="example-number-input">
             @if ($errors->has('stock'))
                <span class="help-block">{{ $errors->first('stock') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="example-email-input" class="col-xs-1 col-form-label">Deskripsi</label>
          <div class="col-xs-10 {{ $errors->has('description') ? ' has-error ' : '' }}">
          <textarea name="description" class="form-control"></textarea>
          </div>
          @if ($errors->has('description'))
                <span class="help-block">{{ $errors->first('description') }}</span>
            @endif
        </div>
        {{ csrf_field() }}
        <input type="submit" class="btn btn-primary ">
        <a href="{{ route('food.index') }}" class="btn btn-warning ">Cancel</a>
        </form>
@endsection

resources/views/backend/food/edit.blade.php
@extends('backend.templates.default')
@section('content')
    <form action="{{ route('food.update',$food->id) }}" method="post" enctype="multipart/form-data">
   {{ method_field('PUT') }}
    <h1 align="center" class="panel panel-heading">Edit Makanan</h1>
        <div class="form-group row">
          <label for="name_food" class="col-xs-1 col-form-label">Name</label>
          <div class="col-xs-10 {{ $errors->has('name_food') ? ' has-error ' : '' }}">
            <input value="{{ $food->name_food }}" class="form-control" type="text" name="name_food"  >
          @if ($errors->has('name_food'))
            <span class="help-block">{{ $errors->first('name_food') }}</span>
          @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="price" class="col-xs-1 col-form-label">Price</label>
           <div class="col-xs-10 {{ $errors->has('price') ? ' has-error ' : '' }}">
            <input value="{{ $food->price }}" class="form-control" type="number" name="price" >
            @if ($errors->has('price'))
                <span class="help-block">{{ $errors->first('price') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="example-url-input" class="col-xs-1 col-form-label">Image</label>
          <div class="col-xs-10 {{ $errors->has('image') ? ' has-error ' : '' }}">
            <input class="form-control" type="file" name="image" accept="image/*" id="example-url-input">
          @if ($errors->has('image'))
                <span class="help-block">{{ $errors->first('image') }}</span>
          @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="example-email-input" class="col-xs-1 col-form-label">Diskon</label>
          <div class="col-xs-10 {{ $errors->has('discount') ? ' has-error ' : '' }}">
            <input value="{{ $food->discount }}" class="form-control" name="discount" type="number" value="" id="example-email-input">
             @if ($errors->has('discount'))
                <span class="help-block">{{ $errors->first('discount') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="example-number-input" class="col-xs-1 col-form-label">Stok</label>
          <div class="col-xs-10 {{ $errors->has('stock') ? ' has-error ' : '' }}">
            <input value="{{ $food->stock }}" class="form-control" name="stock" type="number" value="" id="example-number-input">
             @if ($errors->has('stock'))
                <span class="help-block">{{ $errors->first('stock') }}</span>
            @endif
          </div>
        </div>
        <div class="form-group row">
          <label for="example-email-input" class="col-xs-1 col-form-label">Deskripsi</label>
          <div class="col-xs-10 {{ $errors->has('description') ? ' has-error ' : '' }}">
          <textarea name="description" class="form-control">{{ $food->description }}</textarea>
          </div>
          @if ($errors->has('description'))
                <span class="help-block">{{ $errors->first('description') }}</span>
            @endif
        </div>
        {{ csrf_field() }}
        <input type="submit" class="btn btn-primary ">
        <a href="{{ route('index') }}" class="btn btn-warning ">Cancel</a>
        </form>
@endsection

resources/views/backend/food/index.blade.php
@extends('backend.templates.default')
@section('content')
    <h1 class="panel panel-heading">Daftar Makanan</h1><hr>
      <div class="form-group">
        <a href="{{ route('food.create') }}" class="btn btn-primary">Tambah Makanan</a>
          <form action="" method="get" accept-charset="utf-8">
            <div class="col-md-2 col-xs-offset-9">
            <input type="text" name="name" value="{{ Request::old('name') }}" placeholder="Nama.." class="form-control">
          </div>
          <input type="submit" name="" value="Cari" class="col-md-1 btn btn-primary pull-right">
          </form>
      </div>
      <div class="input-group col-md-3 pull-right">
        {{-- <input type="text" class="form-control" placeholder="Search.." aria-describedby="basic-addon2">
        <span class="input-group-addon" id="basic-addon2">
          <input type="submit" value="Go">
        </span> --}}
      </div>
      <br>
      <br>
      <table class="table table-striped col-md-3">
      <thead>
        <tr>
          <th>Nama Makanan</th>
          <th>Harga</th>
          <th>Stok</th>
          <th>Diskon</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
      @if ($foods->count() == 0)
        <tr>
          <td colspan="5" align="center"><h4>Data Kosong!</h4></td>
        </tr>
      @else
      @foreach ($foods as $food)
        <tr>
            <td>{{ $food->name_food }}</td>
            <td>Rp.{{ number_format($food->price) }}</td>
            <td>{{ $food->stock }}</td>
            <td>{{ $food->discount }}%</td>
            <td>
            <a href="{{ route('food.show',$food->id) }}" class="btn btn-primary fa fa-info-circle"></a>
            <a href="{{ route('food.edit',$food->id) }}" class="btn btn-warning fa fa-pencil-square-o"></a>
            <!-- <a type="button" onClick="hapus();" class="btn btn-danger fa fa-trash-o hapus"></a> -->
            </td>
        </tr>
      @endforeach
      <!-- <script>
        function hapus(){
          if (confirm("apakah anda yakin inginn menghapus ? ")) {
            location.href = "{{ route('food.delete',$food->id) }}";
          }
        }
      </script> -->
      </tbody>
      @endif
    </table>
    {!! $foods->appends([
        'name' => Request::get('name'),
      ])->render() !!}
@endsection

resources/views/backend/food/show.blade.php
@extends('backend.templates.default')
@section('content')
    <h1 class="panel panel-heading">Detail Makanan</h1><hr>
                  <div class="row">
                      <div class="col-md-6">
                          <div class="thumbnail">
                                <img src="{{ $food->image }}" alt="">
                          </div>
                          <a href="{{ route('food.index') }}" class="btn btn-primary">Kembali</a>
                      </div>
                        <div class="col-md-6">
                          <div class="panel panel-body">
                              <table class="table table-bordered">
                                    <tr>
                                        <p>
                                            <td>
                                                <p><b>Nama Makanan</b></p>
                                            </td>
                                            <td>
                                                <p>{{ $food->name_food }}</p>
                                            </td>
                                        </p>
                                    </tr>
                                    <tr>
                                        <p>
                                            <td>
                                                <p><b>Harga</b></p>
                                            </td>
                                            <td>
                                                <p>
                                                Rp.{{ number_format($food->price) }}
                                                </p>
                                            </td>
                                        </p>
                                    </tr>
                                    <tr>
                                        <p>
                                            <td>
                                                <p><b>Diskon</b></p>
                                            </td>
                                            <td>
                                                <p>{{ $food->discount }}</p>
                                            </td>
                                        </p>
                                    </tr>
                                    <tr>
                                        <p>
                                            <td>
                                                <p><b>Deskripsi</b></p>
                                            </td>
                                            <td>
                                                <p>
                                                {{ $food->description }}
                                                </p>
                                            </td>
                                        </p>
                                    </tr>
                                    <tr>
                                        <td>
                                            <p><b>Stok</b></p>
                                        </td>
                                        <td>
                                            <p>
                                            {{ $food->stock }}
                                            </p>
                                        </td>
                                    </tr>
                                </table>
                          </div>
                        </div>
                  </div>

@stop